# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build nx-blog-app`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t nx-blog-app`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system nx-blog-app && \
          adduser --system -G nx-blog-app nx-blog-app

COPY dist/nx-blog-app nx-blog-app
RUN chown -R nx-blog-app:nx-blog-app .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix nx-blog-app --omit=dev -f install

CMD [ "node", "nx-blog-app" ]
